//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject: Codable { 


    public var file: URL?

    public init(file: URL?) {
        self.file = file
    }

}
